# Generated by Django 2.0.7 on 2019-02-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('fatername', models.CharField(max_length=200)),
                ('mothername', models.CharField(max_length=200)),
                ('school', models.BooleanField()),
                ('college', models.BooleanField()),
                ('university', models.BooleanField()),
            ],
        ),
    ]
