# Generated by Django 2.0.7 on 2019-02-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fatername',
            new_name='fathername',
        ),
    ]
